import os

class DefaultConfig:
    EXTERNAL_ENDPOINT = os.environ.get("ExternalEndpoint", "http://localhost:4566")
    INTERNAL_ENDPOINT = os.environ.get("InternalEndpoint", "http://host.docker.internal:4566")
    NOSQL_TABLE_DEFAULT_NAME = os.environ.get("TableName", "RoomStatus")
    ERROR_QUEUE_DEFAULT_NAME = os.environ.get("ErrorQueueDefName", "errors")
    DEWPOINT_QUEUE_DEFAULT_NAME = os.environ.get("DewPointQueueDefName", "dewPointQueue")
    DOOR_QUEUE_DEFAULT_NAME = os.environ.get("DoorQueueDefName", "doorQueue")
    VIBRATION_QUEUE_DEFAULT_NAME = os.environ.get("VibQueueDefName", "vibrationQueue")
    VAPOR_PRESSURE_QUEUE_DEFAULT_NAME = os.environ.get("VaporPressQueue", "vaporPressureQueue")
    TEMPERATURE_QUEUE_DEFAULT_NAME = os.environ.get("TemperatureQueue", "temperatureQueue")
    BUCKET_DUMP_DEFAULT_NAME = os.environ.get("S3DefaultName", "sensorbucket")
    DEFAULT_FAILURE_RATE = os.environ.get("DefaultFailure", 0.5)
    KINESIS_DATA_STREAM = os.environ.get("KinesisName", "doorStream")
    SNS_TOPIC_DEFAULT_NAME = os.environ.get("SNSTopic", "notificationTopic")
    SNS_DEFAULT_TOPIC_ARN = os.environ.get("SNSTopicArn", "")
    WAITING_TIME = os.environ.get("DoorWaitingTime", 600)
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "")
    BOT_ID = os.environ.get("BOT_ID", "")
    API_ID = os.environ.get("API_ID", "")
    ROOM_CONFIGURATION = os.environ.get("rooms", ['Full-bodied-reds', 'Light-to-medium-bodied-reds', 'Dry-Whites', 'Sparklings', 'Sweets'])
