import logging
import json
import datetime
import boto3
from config import DefaultConfig
from botocore.exceptions import ClientError

'''Activates every time there's an error generated by a sensor. Writes the error on SNS Topic '''
# TODO
def lambda_handler(event, context):
    pass
